# Generated by Django 2.1.7 on 2019-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catter', '0002_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
        migrations.AddField(
            model_name='cat',
            name='imageUrl',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
